apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodejs
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/front: "true"
        io.kompose.service: nodejs
    spec:
      containers:
      - image: nodejs
        imagePullPolicy: ""
        name: nodejs
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: nodejs-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: nodejs-claim0
        persistentVolumeClaim:
          claimName: nodejs-claim0
status: {}
